/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevPreviewRouteImport } from './routes/dev-preview'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedGroupsRouteImport } from './routes/_authenticated/groups'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedPresentLessonIdRouteImport } from './routes/_authenticated/present/$lessonId'
import { Route as AuthenticatedControlLessonIdRouteImport } from './routes/_authenticated/control/$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev-preview',
  path: '/dev-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGroupsRoute = AuthenticatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPresentLessonIdRoute =
  AuthenticatedPresentLessonIdRouteImport.update({
    id: '/present/$lessonId',
    path: '/present/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlLessonIdRoute =
  AuthenticatedControlLessonIdRouteImport.update({
    id: '/control/$lessonId',
    path: '/control/$lessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/control/$lessonId': typeof AuthenticatedControlLessonIdRoute
  '/present/$lessonId': typeof AuthenticatedPresentLessonIdRoute
}
export interface FileRoutesByTo {
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/finances': typeof AuthenticatedFinancesRoute
  '/groups': typeof AuthenticatedGroupsRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/': typeof AuthenticatedIndexRoute
  '/control/$lessonId': typeof AuthenticatedControlLessonIdRoute
  '/present/$lessonId': typeof AuthenticatedPresentLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRoute
  '/_authenticated/groups': typeof AuthenticatedGroupsRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/control/$lessonId': typeof AuthenticatedControlLessonIdRoute
  '/_authenticated/present/$lessonId': typeof AuthenticatedPresentLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-preview'
    | '/login'
    | '/finances'
    | '/groups'
    | '/partners'
    | '/students'
    | '/studio'
    | '/control/$lessonId'
    | '/present/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dev-preview'
    | '/login'
    | '/finances'
    | '/groups'
    | '/partners'
    | '/students'
    | '/studio'
    | '/'
    | '/control/$lessonId'
    | '/present/$lessonId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/dev-preview'
    | '/login'
    | '/_authenticated/finances'
    | '/_authenticated/groups'
    | '/_authenticated/partners'
    | '/_authenticated/students'
    | '/_authenticated/studio'
    | '/_authenticated/'
    | '/_authenticated/control/$lessonId'
    | '/_authenticated/present/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DevPreviewRoute: typeof DevPreviewRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview': {
      id: '/dev-preview'
      path: '/dev-preview'
      fullPath: '/dev-preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/groups': {
      id: '/_authenticated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/present/$lessonId': {
      id: '/_authenticated/present/$lessonId'
      path: '/present/$lessonId'
      fullPath: '/present/$lessonId'
      preLoaderRoute: typeof AuthenticatedPresentLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control/$lessonId': {
      id: '/_authenticated/control/$lessonId'
      path: '/control/$lessonId'
      fullPath: '/control/$lessonId'
      preLoaderRoute: typeof AuthenticatedControlLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRoute
  AuthenticatedGroupsRoute: typeof AuthenticatedGroupsRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedControlLessonIdRoute: typeof AuthenticatedControlLessonIdRoute
  AuthenticatedPresentLessonIdRoute: typeof AuthenticatedPresentLessonIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFinancesRoute: AuthenticatedFinancesRoute,
  AuthenticatedGroupsRoute: AuthenticatedGroupsRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedControlLessonIdRoute: AuthenticatedControlLessonIdRoute,
  AuthenticatedPresentLessonIdRoute: AuthenticatedPresentLessonIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DevPreviewRoute: DevPreviewRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
