/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevPreviewRouteImport } from './routes/dev-preview'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedStudentRouteRouteImport } from './routes/_authenticated/_student/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/_student/profile'
import { Route as AuthenticatedStudentPracticeRouteImport } from './routes/_authenticated/_student/practice'
import { Route as AuthenticatedStudentOnboardingRouteImport } from './routes/_authenticated/_student/onboarding'
import { Route as AuthenticatedStudentMyLessonsRouteImport } from './routes/_authenticated/_student/my-lessons'
import { Route as AuthenticatedStudentMyHomeworkRouteImport } from './routes/_authenticated/_student/my-homework'
import { Route as AuthenticatedStudentMyContextRouteImport } from './routes/_authenticated/_student/my-context'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated/_admin/teachers'
import { Route as AuthenticatedAdminScheduleRouteImport } from './routes/_authenticated/_admin/schedule'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/_admin/partners'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/_admin/modules'
import { Route as AuthenticatedAdminLessonsRouteImport } from './routes/_authenticated/_admin/lessons'
import { Route as AuthenticatedAdminFinancesRouteImport } from './routes/_authenticated/_admin/finances'
import { Route as AuthenticatedStudentLearnIndexRouteImport } from './routes/_authenticated/_student/learn/index'
import { Route as AuthenticatedAdminStudioIndexRouteImport } from './routes/_authenticated/_admin/studio/index'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated/_admin/students/index'
import { Route as AuthenticatedAdminGroupsIndexRouteImport } from './routes/_authenticated/_admin/groups/index'
import { Route as AuthenticatedAdminCorrectionsIndexRouteImport } from './routes/_authenticated/_admin/corrections/index'
import { Route as AuthenticatedStudentLearnLessonIdRouteImport } from './routes/_authenticated/_student/learn/$lessonId'
import { Route as AuthenticatedStudentHomeworkHomeworkIdRouteImport } from './routes/_authenticated/_student/homework/$homeworkId'
import { Route as AuthenticatedAdminStudentsStudentIdRouteImport } from './routes/_authenticated/_admin/students/$studentId'
import { Route as AuthenticatedAdminPresentLessonIdRouteImport } from './routes/_authenticated/_admin/present/$lessonId'
import { Route as AuthenticatedAdminGroupsGroupIdRouteImport } from './routes/_authenticated/_admin/groups/$groupId'
import { Route as AuthenticatedAdminCorrectionsSubmissionIdRouteImport } from './routes/_authenticated/_admin/corrections/$submissionId'
import { Route as AuthenticatedAdminControlLessonIdRouteImport } from './routes/_authenticated/_admin/control/$lessonId'
import { Route as AuthenticatedAdminStudioMaterialLessonIdRouteImport } from './routes/_authenticated/_admin/studio/material.$lessonId'
import { Route as AuthenticatedAdminStudioLessonLessonIdRouteImport } from './routes/_authenticated/_admin/studio/lesson.$lessonId'
import { Route as AuthenticatedAdminStudioHomeworkHomeworkIdRouteImport } from './routes/_authenticated/_admin/studio/homework.$homeworkId'
import { Route as AuthenticatedAdminStudioGroupGroupIdIndexRouteImport } from './routes/_authenticated/_admin/studio/group.$groupId.index'
import { Route as AuthenticatedAdminStudioAdvancedGroupIdLessonIdRouteImport } from './routes/_authenticated/_admin/studio/advanced.$groupId.$lessonId'
import { Route as AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRouteImport } from './routes/_authenticated/_admin/studio/group.$groupId.material.$lessonId'
import { Route as AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRouteImport } from './routes/_authenticated/_admin/studio/group.$groupId.homework.$homeworkId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewRoute = DevPreviewRouteImport.update({
  id: '/dev-preview',
  path: '/dev-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentRouteRoute =
  AuthenticatedStudentRouteRouteImport.update({
    id: '/_student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentPracticeRoute =
  AuthenticatedStudentPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentOnboardingRoute =
  AuthenticatedStudentOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyLessonsRoute =
  AuthenticatedStudentMyLessonsRouteImport.update({
    id: '/my-lessons',
    path: '/my-lessons',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyHomeworkRoute =
  AuthenticatedStudentMyHomeworkRouteImport.update({
    id: '/my-homework',
    path: '/my-homework',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentMyContextRoute =
  AuthenticatedStudentMyContextRouteImport.update({
    id: '/my-context',
    path: '/my-context',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScheduleRoute =
  AuthenticatedAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLessonsRoute =
  AuthenticatedAdminLessonsRouteImport.update({
    id: '/lessons',
    path: '/lessons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFinancesRoute =
  AuthenticatedAdminFinancesRouteImport.update({
    id: '/finances',
    path: '/finances',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStudentLearnIndexRoute =
  AuthenticatedStudentLearnIndexRouteImport.update({
    id: '/learn/',
    path: '/learn/',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminStudioIndexRoute =
  AuthenticatedAdminStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGroupsIndexRoute =
  AuthenticatedAdminGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCorrectionsIndexRoute =
  AuthenticatedAdminCorrectionsIndexRouteImport.update({
    id: '/corrections/',
    path: '/corrections/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedStudentLearnLessonIdRoute =
  AuthenticatedStudentLearnLessonIdRouteImport.update({
    id: '/learn/$lessonId',
    path: '/learn/$lessonId',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedStudentHomeworkHomeworkIdRoute =
  AuthenticatedStudentHomeworkHomeworkIdRouteImport.update({
    id: '/homework/$homeworkId',
    path: '/homework/$homeworkId',
    getParentRoute: () => AuthenticatedStudentRouteRoute,
  } as any)
const AuthenticatedAdminStudentsStudentIdRoute =
  AuthenticatedAdminStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPresentLessonIdRoute =
  AuthenticatedAdminPresentLessonIdRouteImport.update({
    id: '/present/$lessonId',
    path: '/present/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminGroupsGroupIdRoute =
  AuthenticatedAdminGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCorrectionsSubmissionIdRoute =
  AuthenticatedAdminCorrectionsSubmissionIdRouteImport.update({
    id: '/corrections/$submissionId',
    path: '/corrections/$submissionId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminControlLessonIdRoute =
  AuthenticatedAdminControlLessonIdRouteImport.update({
    id: '/control/$lessonId',
    path: '/control/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioMaterialLessonIdRoute =
  AuthenticatedAdminStudioMaterialLessonIdRouteImport.update({
    id: '/studio/material/$lessonId',
    path: '/studio/material/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioLessonLessonIdRoute =
  AuthenticatedAdminStudioLessonLessonIdRouteImport.update({
    id: '/studio/lesson/$lessonId',
    path: '/studio/lesson/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioHomeworkHomeworkIdRoute =
  AuthenticatedAdminStudioHomeworkHomeworkIdRouteImport.update({
    id: '/studio/homework/$homeworkId',
    path: '/studio/homework/$homeworkId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioGroupGroupIdIndexRoute =
  AuthenticatedAdminStudioGroupGroupIdIndexRouteImport.update({
    id: '/studio/group/$groupId/',
    path: '/studio/group/$groupId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute =
  AuthenticatedAdminStudioAdvancedGroupIdLessonIdRouteImport.update({
    id: '/studio/advanced/$groupId/$lessonId',
    path: '/studio/advanced/$groupId/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute =
  AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRouteImport.update({
    id: '/studio/group/$groupId/material/$lessonId',
    path: '/studio/group/$groupId/material/$lessonId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute =
  AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRouteImport.update({
    id: '/studio/group/$groupId/homework/$homeworkId',
    path: '/studio/group/$groupId/homework/$homeworkId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/finances': typeof AuthenticatedAdminFinancesRoute
  '/lessons': typeof AuthenticatedAdminLessonsRoute
  '/modules': typeof AuthenticatedAdminModulesRoute
  '/partners': typeof AuthenticatedAdminPartnersRoute
  '/schedule': typeof AuthenticatedAdminScheduleRoute
  '/teachers': typeof AuthenticatedAdminTeachersRoute
  '/my-context': typeof AuthenticatedStudentMyContextRoute
  '/my-homework': typeof AuthenticatedStudentMyHomeworkRoute
  '/my-lessons': typeof AuthenticatedStudentMyLessonsRoute
  '/onboarding': typeof AuthenticatedStudentOnboardingRoute
  '/practice': typeof AuthenticatedStudentPracticeRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/control/$lessonId': typeof AuthenticatedAdminControlLessonIdRoute
  '/corrections/$submissionId': typeof AuthenticatedAdminCorrectionsSubmissionIdRoute
  '/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/present/$lessonId': typeof AuthenticatedAdminPresentLessonIdRoute
  '/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/homework/$homeworkId': typeof AuthenticatedStudentHomeworkHomeworkIdRoute
  '/learn/$lessonId': typeof AuthenticatedStudentLearnLessonIdRoute
  '/corrections/': typeof AuthenticatedAdminCorrectionsIndexRoute
  '/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/studio/': typeof AuthenticatedAdminStudioIndexRoute
  '/learn/': typeof AuthenticatedStudentLearnIndexRoute
  '/studio/homework/$homeworkId': typeof AuthenticatedAdminStudioHomeworkHomeworkIdRoute
  '/studio/lesson/$lessonId': typeof AuthenticatedAdminStudioLessonLessonIdRoute
  '/studio/material/$lessonId': typeof AuthenticatedAdminStudioMaterialLessonIdRoute
  '/studio/advanced/$groupId/$lessonId': typeof AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute
  '/studio/group/$groupId/': typeof AuthenticatedAdminStudioGroupGroupIdIndexRoute
  '/studio/group/$groupId/homework/$homeworkId': typeof AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute
  '/studio/group/$groupId/material/$lessonId': typeof AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/finances': typeof AuthenticatedAdminFinancesRoute
  '/lessons': typeof AuthenticatedAdminLessonsRoute
  '/modules': typeof AuthenticatedAdminModulesRoute
  '/partners': typeof AuthenticatedAdminPartnersRoute
  '/schedule': typeof AuthenticatedAdminScheduleRoute
  '/teachers': typeof AuthenticatedAdminTeachersRoute
  '/my-context': typeof AuthenticatedStudentMyContextRoute
  '/my-homework': typeof AuthenticatedStudentMyHomeworkRoute
  '/my-lessons': typeof AuthenticatedStudentMyLessonsRoute
  '/onboarding': typeof AuthenticatedStudentOnboardingRoute
  '/practice': typeof AuthenticatedStudentPracticeRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/control/$lessonId': typeof AuthenticatedAdminControlLessonIdRoute
  '/corrections/$submissionId': typeof AuthenticatedAdminCorrectionsSubmissionIdRoute
  '/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/present/$lessonId': typeof AuthenticatedAdminPresentLessonIdRoute
  '/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/homework/$homeworkId': typeof AuthenticatedStudentHomeworkHomeworkIdRoute
  '/learn/$lessonId': typeof AuthenticatedStudentLearnLessonIdRoute
  '/corrections': typeof AuthenticatedAdminCorrectionsIndexRoute
  '/groups': typeof AuthenticatedAdminGroupsIndexRoute
  '/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/studio': typeof AuthenticatedAdminStudioIndexRoute
  '/learn': typeof AuthenticatedStudentLearnIndexRoute
  '/studio/homework/$homeworkId': typeof AuthenticatedAdminStudioHomeworkHomeworkIdRoute
  '/studio/lesson/$lessonId': typeof AuthenticatedAdminStudioLessonLessonIdRoute
  '/studio/material/$lessonId': typeof AuthenticatedAdminStudioMaterialLessonIdRoute
  '/studio/advanced/$groupId/$lessonId': typeof AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute
  '/studio/group/$groupId': typeof AuthenticatedAdminStudioGroupGroupIdIndexRoute
  '/studio/group/$groupId/homework/$homeworkId': typeof AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute
  '/studio/group/$groupId/material/$lessonId': typeof AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/dev-preview': typeof DevPreviewRoute
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteRouteWithChildren
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/_admin/finances': typeof AuthenticatedAdminFinancesRoute
  '/_authenticated/_admin/lessons': typeof AuthenticatedAdminLessonsRoute
  '/_authenticated/_admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/_admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/_admin/schedule': typeof AuthenticatedAdminScheduleRoute
  '/_authenticated/_admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/_student/my-context': typeof AuthenticatedStudentMyContextRoute
  '/_authenticated/_student/my-homework': typeof AuthenticatedStudentMyHomeworkRoute
  '/_authenticated/_student/my-lessons': typeof AuthenticatedStudentMyLessonsRoute
  '/_authenticated/_student/onboarding': typeof AuthenticatedStudentOnboardingRoute
  '/_authenticated/_student/practice': typeof AuthenticatedStudentPracticeRoute
  '/_authenticated/_student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/_admin/control/$lessonId': typeof AuthenticatedAdminControlLessonIdRoute
  '/_authenticated/_admin/corrections/$submissionId': typeof AuthenticatedAdminCorrectionsSubmissionIdRoute
  '/_authenticated/_admin/groups/$groupId': typeof AuthenticatedAdminGroupsGroupIdRoute
  '/_authenticated/_admin/present/$lessonId': typeof AuthenticatedAdminPresentLessonIdRoute
  '/_authenticated/_admin/students/$studentId': typeof AuthenticatedAdminStudentsStudentIdRoute
  '/_authenticated/_student/homework/$homeworkId': typeof AuthenticatedStudentHomeworkHomeworkIdRoute
  '/_authenticated/_student/learn/$lessonId': typeof AuthenticatedStudentLearnLessonIdRoute
  '/_authenticated/_admin/corrections/': typeof AuthenticatedAdminCorrectionsIndexRoute
  '/_authenticated/_admin/groups/': typeof AuthenticatedAdminGroupsIndexRoute
  '/_authenticated/_admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/_admin/studio/': typeof AuthenticatedAdminStudioIndexRoute
  '/_authenticated/_student/learn/': typeof AuthenticatedStudentLearnIndexRoute
  '/_authenticated/_admin/studio/homework/$homeworkId': typeof AuthenticatedAdminStudioHomeworkHomeworkIdRoute
  '/_authenticated/_admin/studio/lesson/$lessonId': typeof AuthenticatedAdminStudioLessonLessonIdRoute
  '/_authenticated/_admin/studio/material/$lessonId': typeof AuthenticatedAdminStudioMaterialLessonIdRoute
  '/_authenticated/_admin/studio/advanced/$groupId/$lessonId': typeof AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute
  '/_authenticated/_admin/studio/group/$groupId/': typeof AuthenticatedAdminStudioGroupGroupIdIndexRoute
  '/_authenticated/_admin/studio/group/$groupId/homework/$homeworkId': typeof AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute
  '/_authenticated/_admin/studio/group/$groupId/material/$lessonId': typeof AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev-preview'
    | '/login'
    | '/change-password'
    | '/finances'
    | '/lessons'
    | '/modules'
    | '/partners'
    | '/schedule'
    | '/teachers'
    | '/my-context'
    | '/my-homework'
    | '/my-lessons'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/control/$lessonId'
    | '/corrections/$submissionId'
    | '/groups/$groupId'
    | '/present/$lessonId'
    | '/students/$studentId'
    | '/homework/$homeworkId'
    | '/learn/$lessonId'
    | '/corrections/'
    | '/groups/'
    | '/students/'
    | '/studio/'
    | '/learn/'
    | '/studio/homework/$homeworkId'
    | '/studio/lesson/$lessonId'
    | '/studio/material/$lessonId'
    | '/studio/advanced/$groupId/$lessonId'
    | '/studio/group/$groupId/'
    | '/studio/group/$groupId/homework/$homeworkId'
    | '/studio/group/$groupId/material/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev-preview'
    | '/login'
    | '/change-password'
    | '/finances'
    | '/lessons'
    | '/modules'
    | '/partners'
    | '/schedule'
    | '/teachers'
    | '/my-context'
    | '/my-homework'
    | '/my-lessons'
    | '/onboarding'
    | '/practice'
    | '/profile'
    | '/control/$lessonId'
    | '/corrections/$submissionId'
    | '/groups/$groupId'
    | '/present/$lessonId'
    | '/students/$studentId'
    | '/homework/$homeworkId'
    | '/learn/$lessonId'
    | '/corrections'
    | '/groups'
    | '/students'
    | '/studio'
    | '/learn'
    | '/studio/homework/$homeworkId'
    | '/studio/lesson/$lessonId'
    | '/studio/material/$lessonId'
    | '/studio/advanced/$groupId/$lessonId'
    | '/studio/group/$groupId'
    | '/studio/group/$groupId/homework/$homeworkId'
    | '/studio/group/$groupId/material/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dev-preview'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/_student'
    | '/_authenticated/change-password'
    | '/_authenticated/_admin/finances'
    | '/_authenticated/_admin/lessons'
    | '/_authenticated/_admin/modules'
    | '/_authenticated/_admin/partners'
    | '/_authenticated/_admin/schedule'
    | '/_authenticated/_admin/teachers'
    | '/_authenticated/_student/my-context'
    | '/_authenticated/_student/my-homework'
    | '/_authenticated/_student/my-lessons'
    | '/_authenticated/_student/onboarding'
    | '/_authenticated/_student/practice'
    | '/_authenticated/_student/profile'
    | '/_authenticated/_admin/control/$lessonId'
    | '/_authenticated/_admin/corrections/$submissionId'
    | '/_authenticated/_admin/groups/$groupId'
    | '/_authenticated/_admin/present/$lessonId'
    | '/_authenticated/_admin/students/$studentId'
    | '/_authenticated/_student/homework/$homeworkId'
    | '/_authenticated/_student/learn/$lessonId'
    | '/_authenticated/_admin/corrections/'
    | '/_authenticated/_admin/groups/'
    | '/_authenticated/_admin/students/'
    | '/_authenticated/_admin/studio/'
    | '/_authenticated/_student/learn/'
    | '/_authenticated/_admin/studio/homework/$homeworkId'
    | '/_authenticated/_admin/studio/lesson/$lessonId'
    | '/_authenticated/_admin/studio/material/$lessonId'
    | '/_authenticated/_admin/studio/advanced/$groupId/$lessonId'
    | '/_authenticated/_admin/studio/group/$groupId/'
    | '/_authenticated/_admin/studio/group/$groupId/homework/$homeworkId'
    | '/_authenticated/_admin/studio/group/$groupId/material/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DevPreviewRoute: typeof DevPreviewRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview': {
      id: '/dev-preview'
      path: '/dev-preview'
      fullPath: '/dev-preview'
      preLoaderRoute: typeof DevPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_student/profile': {
      id: '/_authenticated/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/practice': {
      id: '/_authenticated/_student/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedStudentPracticeRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/onboarding': {
      id: '/_authenticated/_student/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedStudentOnboardingRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-lessons': {
      id: '/_authenticated/_student/my-lessons'
      path: '/my-lessons'
      fullPath: '/my-lessons'
      preLoaderRoute: typeof AuthenticatedStudentMyLessonsRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-homework': {
      id: '/_authenticated/_student/my-homework'
      path: '/my-homework'
      fullPath: '/my-homework'
      preLoaderRoute: typeof AuthenticatedStudentMyHomeworkRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/my-context': {
      id: '/_authenticated/_student/my-context'
      path: '/my-context'
      fullPath: '/my-context'
      preLoaderRoute: typeof AuthenticatedStudentMyContextRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_admin/teachers': {
      id: '/_authenticated/_admin/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/schedule': {
      id: '/_authenticated/_admin/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/partners': {
      id: '/_authenticated/_admin/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/modules': {
      id: '/_authenticated/_admin/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/lessons': {
      id: '/_authenticated/_admin/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AuthenticatedAdminLessonsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/finances': {
      id: '/_authenticated/_admin/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedAdminFinancesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_student/learn/': {
      id: '/_authenticated/_student/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof AuthenticatedStudentLearnIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_admin/studio/': {
      id: '/_authenticated/_admin/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedAdminStudioIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/students/': {
      id: '/_authenticated/_admin/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/groups/': {
      id: '/_authenticated/_admin/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedAdminGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/corrections/': {
      id: '/_authenticated/_admin/corrections/'
      path: '/corrections'
      fullPath: '/corrections/'
      preLoaderRoute: typeof AuthenticatedAdminCorrectionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_student/learn/$lessonId': {
      id: '/_authenticated/_student/learn/$lessonId'
      path: '/learn/$lessonId'
      fullPath: '/learn/$lessonId'
      preLoaderRoute: typeof AuthenticatedStudentLearnLessonIdRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_student/homework/$homeworkId': {
      id: '/_authenticated/_student/homework/$homeworkId'
      path: '/homework/$homeworkId'
      fullPath: '/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedStudentHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedStudentRouteRoute
    }
    '/_authenticated/_admin/students/$studentId': {
      id: '/_authenticated/_admin/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AuthenticatedAdminStudentsStudentIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/present/$lessonId': {
      id: '/_authenticated/_admin/present/$lessonId'
      path: '/present/$lessonId'
      fullPath: '/present/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminPresentLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/groups/$groupId': {
      id: '/_authenticated/_admin/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AuthenticatedAdminGroupsGroupIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/corrections/$submissionId': {
      id: '/_authenticated/_admin/corrections/$submissionId'
      path: '/corrections/$submissionId'
      fullPath: '/corrections/$submissionId'
      preLoaderRoute: typeof AuthenticatedAdminCorrectionsSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/control/$lessonId': {
      id: '/_authenticated/_admin/control/$lessonId'
      path: '/control/$lessonId'
      fullPath: '/control/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminControlLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/material/$lessonId': {
      id: '/_authenticated/_admin/studio/material/$lessonId'
      path: '/studio/material/$lessonId'
      fullPath: '/studio/material/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminStudioMaterialLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/lesson/$lessonId': {
      id: '/_authenticated/_admin/studio/lesson/$lessonId'
      path: '/studio/lesson/$lessonId'
      fullPath: '/studio/lesson/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminStudioLessonLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/homework/$homeworkId': {
      id: '/_authenticated/_admin/studio/homework/$homeworkId'
      path: '/studio/homework/$homeworkId'
      fullPath: '/studio/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedAdminStudioHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/group/$groupId/': {
      id: '/_authenticated/_admin/studio/group/$groupId/'
      path: '/studio/group/$groupId'
      fullPath: '/studio/group/$groupId/'
      preLoaderRoute: typeof AuthenticatedAdminStudioGroupGroupIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/advanced/$groupId/$lessonId': {
      id: '/_authenticated/_admin/studio/advanced/$groupId/$lessonId'
      path: '/studio/advanced/$groupId/$lessonId'
      fullPath: '/studio/advanced/$groupId/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminStudioAdvancedGroupIdLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/group/$groupId/material/$lessonId': {
      id: '/_authenticated/_admin/studio/group/$groupId/material/$lessonId'
      path: '/studio/group/$groupId/material/$lessonId'
      fullPath: '/studio/group/$groupId/material/$lessonId'
      preLoaderRoute: typeof AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/studio/group/$groupId/homework/$homeworkId': {
      id: '/_authenticated/_admin/studio/group/$groupId/homework/$homeworkId'
      path: '/studio/group/$groupId/homework/$homeworkId'
      fullPath: '/studio/group/$groupId/homework/$homeworkId'
      preLoaderRoute: typeof AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminFinancesRoute: typeof AuthenticatedAdminFinancesRoute
  AuthenticatedAdminLessonsRoute: typeof AuthenticatedAdminLessonsRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminScheduleRoute: typeof AuthenticatedAdminScheduleRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
  AuthenticatedAdminControlLessonIdRoute: typeof AuthenticatedAdminControlLessonIdRoute
  AuthenticatedAdminCorrectionsSubmissionIdRoute: typeof AuthenticatedAdminCorrectionsSubmissionIdRoute
  AuthenticatedAdminGroupsGroupIdRoute: typeof AuthenticatedAdminGroupsGroupIdRoute
  AuthenticatedAdminPresentLessonIdRoute: typeof AuthenticatedAdminPresentLessonIdRoute
  AuthenticatedAdminStudentsStudentIdRoute: typeof AuthenticatedAdminStudentsStudentIdRoute
  AuthenticatedAdminCorrectionsIndexRoute: typeof AuthenticatedAdminCorrectionsIndexRoute
  AuthenticatedAdminGroupsIndexRoute: typeof AuthenticatedAdminGroupsIndexRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
  AuthenticatedAdminStudioIndexRoute: typeof AuthenticatedAdminStudioIndexRoute
  AuthenticatedAdminStudioHomeworkHomeworkIdRoute: typeof AuthenticatedAdminStudioHomeworkHomeworkIdRoute
  AuthenticatedAdminStudioLessonLessonIdRoute: typeof AuthenticatedAdminStudioLessonLessonIdRoute
  AuthenticatedAdminStudioMaterialLessonIdRoute: typeof AuthenticatedAdminStudioMaterialLessonIdRoute
  AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute: typeof AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute
  AuthenticatedAdminStudioGroupGroupIdIndexRoute: typeof AuthenticatedAdminStudioGroupGroupIdIndexRoute
  AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute: typeof AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute
  AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute: typeof AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminFinancesRoute: AuthenticatedAdminFinancesRoute,
    AuthenticatedAdminLessonsRoute: AuthenticatedAdminLessonsRoute,
    AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
    AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
    AuthenticatedAdminScheduleRoute: AuthenticatedAdminScheduleRoute,
    AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
    AuthenticatedAdminControlLessonIdRoute:
      AuthenticatedAdminControlLessonIdRoute,
    AuthenticatedAdminCorrectionsSubmissionIdRoute:
      AuthenticatedAdminCorrectionsSubmissionIdRoute,
    AuthenticatedAdminGroupsGroupIdRoute: AuthenticatedAdminGroupsGroupIdRoute,
    AuthenticatedAdminPresentLessonIdRoute:
      AuthenticatedAdminPresentLessonIdRoute,
    AuthenticatedAdminStudentsStudentIdRoute:
      AuthenticatedAdminStudentsStudentIdRoute,
    AuthenticatedAdminCorrectionsIndexRoute:
      AuthenticatedAdminCorrectionsIndexRoute,
    AuthenticatedAdminGroupsIndexRoute: AuthenticatedAdminGroupsIndexRoute,
    AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
    AuthenticatedAdminStudioIndexRoute: AuthenticatedAdminStudioIndexRoute,
    AuthenticatedAdminStudioHomeworkHomeworkIdRoute:
      AuthenticatedAdminStudioHomeworkHomeworkIdRoute,
    AuthenticatedAdminStudioLessonLessonIdRoute:
      AuthenticatedAdminStudioLessonLessonIdRoute,
    AuthenticatedAdminStudioMaterialLessonIdRoute:
      AuthenticatedAdminStudioMaterialLessonIdRoute,
    AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute:
      AuthenticatedAdminStudioAdvancedGroupIdLessonIdRoute,
    AuthenticatedAdminStudioGroupGroupIdIndexRoute:
      AuthenticatedAdminStudioGroupGroupIdIndexRoute,
    AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute:
      AuthenticatedAdminStudioGroupGroupIdHomeworkHomeworkIdRoute,
    AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute:
      AuthenticatedAdminStudioGroupGroupIdMaterialLessonIdRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedStudentRouteRouteChildren {
  AuthenticatedStudentMyContextRoute: typeof AuthenticatedStudentMyContextRoute
  AuthenticatedStudentMyHomeworkRoute: typeof AuthenticatedStudentMyHomeworkRoute
  AuthenticatedStudentMyLessonsRoute: typeof AuthenticatedStudentMyLessonsRoute
  AuthenticatedStudentOnboardingRoute: typeof AuthenticatedStudentOnboardingRoute
  AuthenticatedStudentPracticeRoute: typeof AuthenticatedStudentPracticeRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentHomeworkHomeworkIdRoute: typeof AuthenticatedStudentHomeworkHomeworkIdRoute
  AuthenticatedStudentLearnLessonIdRoute: typeof AuthenticatedStudentLearnLessonIdRoute
  AuthenticatedStudentLearnIndexRoute: typeof AuthenticatedStudentLearnIndexRoute
}

const AuthenticatedStudentRouteRouteChildren: AuthenticatedStudentRouteRouteChildren =
  {
    AuthenticatedStudentMyContextRoute: AuthenticatedStudentMyContextRoute,
    AuthenticatedStudentMyHomeworkRoute: AuthenticatedStudentMyHomeworkRoute,
    AuthenticatedStudentMyLessonsRoute: AuthenticatedStudentMyLessonsRoute,
    AuthenticatedStudentOnboardingRoute: AuthenticatedStudentOnboardingRoute,
    AuthenticatedStudentPracticeRoute: AuthenticatedStudentPracticeRoute,
    AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
    AuthenticatedStudentHomeworkHomeworkIdRoute:
      AuthenticatedStudentHomeworkHomeworkIdRoute,
    AuthenticatedStudentLearnLessonIdRoute:
      AuthenticatedStudentLearnLessonIdRoute,
    AuthenticatedStudentLearnIndexRoute: AuthenticatedStudentLearnIndexRoute,
  }

const AuthenticatedStudentRouteRouteWithChildren =
  AuthenticatedStudentRouteRoute._addFileChildren(
    AuthenticatedStudentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedStudentRouteRoute: typeof AuthenticatedStudentRouteRouteWithChildren
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedStudentRouteRoute: AuthenticatedStudentRouteRouteWithChildren,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DevPreviewRoute: DevPreviewRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
